
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: demo-todo-app
spec:
  selector:
    matchLabels:
      app: demo-todo-app
  replicas: 3
  template:
    metadata:
      name: todo-app-pod
      labels:
        name: todo-app-pod
        app: demo-todo-app
    spec:
      containers:
        - name: todo-app
          image: thoba/todo-list-app
          ports:
            - containerPort: 8080