apiVersion: v1
kind: Service
metadata:
  name: todo-service
  labels:
    name: todo-service
    app: demo-todo-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30010
  selector:
    name: todo-app-pod
    app: demo-todo-app